version: "3"
services:
    notion-page-visibility-checker:
        container_name: notion-page-visibility-checker
        build: .
        tty: true
        environment:
            - NOTION_API_KEY=${NOTION_API_KEY}
            - NOTION_ROOT_PAGE_ID=${NOTION_ROOT_PAGE_ID}
            - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
        env_file:
            - .env
        volumes:
            - ./app:/go/src/app