name: notion-page-visibility-checker-scheduled
on:
  schedule:
    - cron: '0 */1 * * *' # every 1 hour
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NOTION_API: ${{ secrets.NOTION_API_KEY }}
      NOTION_ROOT_PAGE_ID: ${{ secrets.NOTION_ROOT_PAGE_ID }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v3.3.0
      - name: create env file
        run: |
          touch .env
          echo "NOTION_API_KEY=${NOTION_API_KEY}" >> .env
          echo "NOTION_ROOT_PAGE_ID=${NOTION_ROOT_PAGE_ID}" >> .env
          echo "DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}" >> .env
      - name: Build
        run: |
          docker-compose up -d --build
      - name: Run
        run: |
          docker-compose run notion-page-visibility-checker go run main.go discord_messenger.go notion_public_page_url_fetcher.go
